#!/bin/bash
#$ -cwd
#$ -S /bin/bash


SCRIPT_DIR=${1}
INPUT_TSV=${2}
MODE=${3}
NUM_CLONE_TRIAL_START=${4}
NUM_CLONE_TRIAL_END=${5} 
RANDOM_PICK=${6}
AXIS_RATIO=${7}
PARENT_RATIO=${8}
NUM_PARENT=${9}
FP_RATIO=${10}
FP_USEALL=${11}
FP_PRIOR=${12}
TRIAL_NO=${13}
DEPTH_CUTOFF=${14}
MIN_CLUSTER_SIZE=${15}
VERBOSE=${16}
KMEANS_CLUSTERNO=${17}
RANDOM_SEED=${18}
SAMPLENAME=${19}
BENCHMARK_NO=${20}
NPVAF_DIR=${21}
SIMPLE_KMEANS_DIR=${22}
CLEMENT_DIR=${23}
SCICLONE_DIR=${24}
PYCLONEVI_DIR=${25}
QUANTUMCLONE_DIR=${26}
COMBINED_OUTPUT_DIR=${27}
SCORING=${28}
MAKEONE_STRICT=${29}
MAXIMUM_NUM_PARENT=${30}
IMAGE_FORMAT=${31}
VISUALIZATION=${32}
LOGPATH=${33}
LOGPATH_COPY=${34}


#1. 각 RANDOM_SEED에 대해서 tool을 돌린다

echo -e python3 ${SCRIPT_DIR}"/CLEMENT_bm.py" --INPUT_TSV $INPUT_TSV  --IMAGE_FORMAT ${IMAGE_FORMAT} --VISUALIZATION ${VISUALIZATION}  \
    --RANDOM_PICK ${RANDOM_PICK} --AXIS_RATIO $AXIS_RATIO --PARENT_RATIO ${PARENT_RATIO} --NUM_PARENT ${NUM_PARENT} --FP_RATIO $FP_RATIO --FP_USEALL ${FP_USEALL}  --FP_PRIOR ${FP_PRIOR}  \
    --DEPTH_CUTOFF ${DEPTH_CUTOFF} --MIN_CLUSTER_SIZE ${MIN_CLUSTER_SIZE}  --KMEANS_CLUSTERNO ${KMEANS_CLUSTERNO} --RANDOM_SEED ${RANDOM_SEED} \
    --NPVAF_DIR ${NPVAF_DIR} --SIMPLE_KMEANS_DIR ${SIMPLE_KMEANS_DIR} --CLEMENT_DIR ${CLEMENT_DIR} --SCICLONE_DIR ${SCICLONE_DIR} --PYCLONEVI_DIR ${PYCLONEVI_DIR} --QUANTUMCLONE_DIR ${QUANTUMCLONE_DIR} --COMBINED_OUTPUT_DIR ${COMBINED_OUTPUT_DIR} \
    --MODE ${MODE} --SCORING ${SCORING} --MAKEONE_STRICT ${MAKEONE_STRICT} --MAXIMUM_NUM_PARENT ${MAXIMUM_NUM_PARENT} --VERBOSE $VERBOSE   --TRIAL_NO ${TRIAL_NO} --NUM_CLONE_TRIAL_START $NUM_CLONE_TRIAL_START --NUM_CLONE_TRIAL_END $NUM_CLONE_TRIAL_END


python3 ${SCRIPT_DIR}"/CLEMENT_bm.py" --INPUT_TSV $INPUT_TSV --NUM_CLONE_TRIAL_START $NUM_CLONE_TRIAL_START --NUM_CLONE_TRIAL_END $NUM_CLONE_TRIAL_END  \
    --RANDOM_PICK ${RANDOM_PICK} --AXIS_RATIO $AXIS_RATIO --PARENT_RATIO ${PARENT_RATIO} --NUM_PARENT ${NUM_PARENT} --FP_RATIO $FP_RATIO --FP_USEALL ${FP_USEALL}  --FP_PRIOR ${FP_PRIOR} \
    --DEPTH_CUTOFF ${DEPTH_CUTOFF} --MIN_CLUSTER_SIZE ${MIN_CLUSTER_SIZE}  --VERBOSE $VERBOSE --KMEANS_CLUSTERNO ${KMEANS_CLUSTERNO} --RANDOM_SEED ${RANDOM_SEED} \
    --NPVAF_DIR ${NPVAF_DIR} --SIMPLE_KMEANS_DIR ${SIMPLE_KMEANS_DIR} --CLEMENT_DIR ${CLEMENT_DIR} --SCICLONE_DIR ${SCICLONE_DIR} --PYCLONEVI_DIR ${PYCLONEVI_DIR} --QUANTUMCLONE_DIR ${QUANTUMCLONE_DIR} --COMBINED_OUTPUT_DIR ${COMBINED_OUTPUT_DIR} \
    --MODE ${MODE} --SCORING ${SCORING} --MAKEONE_STRICT ${MAKEONE_STRICT} --MAXIMUM_NUM_PARENT ${MAXIMUM_NUM_PARENT}  --TRIAL_NO ${TRIAL_NO} --IMAGE_FORMAT ${IMAGE_FORMAT} --VISUALIZATION ${VISUALIZATION}

echo -e "cp -rf ${LOGPATH} ${LOGPATH_COPY}"
cp -rf ${LOGPATH} ${LOGPATH_COPY}

###########  #$ -l h=!('compute15'|compute16')



